# Generated by Django 2.2.5 on 2019-12-03 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.BooleanField(default=False)),
                ('orderSelected', models.BooleanField(default=False)),
                ('turnMoment', models.IntegerField(blank=True, default=None, null=True)),
                ('round', models.IntegerField(blank=True, default=0, null=True)),
                ('available_colors', models.CharField(default='4dd0e1,ffffa8,ffbsb93', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tabuCode.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('orden', models.IntegerField(default=0)),
                ('turn', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tabuCode.Team')),
            ],
        ),
    ]
