# Generated by Django 2.2.5 on 2019-09-21 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabuCode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('game', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tabuCode.Game')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tabuCode.Team'),
        ),
    ]
