# Generated by Django 2.2.5 on 2019-12-03 01:49

from django.db import migrations, models
import tabuCode.models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuCode', '0002_auto_20191203_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='available_colors',
            field=models.CharField(default=tabuCode.models.get_colors, max_length=100),
        ),
    ]
