# Generated by Django 2.2.5 on 2019-09-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuCode', '0006_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
