# Generated by Django 2.2.5 on 2019-09-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuCode', '0007_person_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='orderSelected',
            field=models.BooleanField(default=False),
        ),
    ]
