# Generated by Django 2.2.5 on 2019-09-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuCode', '0008_game_orderselected'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='turn',
            field=models.BooleanField(default=False),
        ),
    ]
