# Generated by Django 2.2.5 on 2019-09-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuCode', '0009_person_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.AddField(
            model_name='person',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
