# Generated by Django 2.2.5 on 2019-09-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuCode', '0010_auto_20190923_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turnMoment',
            field=models.DateTimeField(default=None),
        ),
    ]
