# Generated by Django 2.2.5 on 2019-09-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuCode', '0011_game_turnmoment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turnMoment',
            field=models.DateTimeField(default=0),
        ),
    ]
