# Generated by Django 2.2.5 on 2019-11-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuCode', '0015_auto_20190924_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
